version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: avaai_postgres
    environment:
      POSTGRES_USER: avaai
      POSTGRES_PASSWORD: avaai_dev_password
      POSTGRES_DB: avaai_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U avaai"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: avaai_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@avaai.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
